local defines = {}

local function add(array)
    for index, string in ipairs(array)do
        local group, single_define = string:match("defines%.([^.]*)%.(.*)")
        if(defines[group] == nil)then
            defines[group] = {}
        end
        defines[group][single_define] = index
    end
end

add({"defines.events.on_tick",
"defines.events.on_gui_click",
"defines.events.on_gui_text_changed",
"defines.events.on_gui_checked_state_changed",
"defines.events.on_entity_died",
"defines.events.on_picked_up_item",
"defines.events.on_built_entity",
"defines.events.on_sector_scanned",
"defines.events.on_player_mined_item",
"defines.events.on_put_item",
"defines.events.on_rocket_launched",
"defines.events.on_preplayer_mined_item",
"defines.events.on_chunk_generated",
"defines.events.on_player_crafted_item",
"defines.events.on_robot_built_entity",
"defines.events.on_robot_pre_mined",
"defines.events.on_robot_mined",
"defines.events.on_research_started",
"defines.events.on_research_finished",
"defines.events.on_player_rotated_entity",
"defines.events.on_marked_for_deconstruction",
"defines.events.on_canceled_deconstruction",
"defines.events.on_trigger_created_entity",
"defines.events.on_train_changed_state",
"defines.events.on_player_created",
"defines.events.on_resource_depleted",
"defines.events.on_player_driving_changed_state",
"defines.events.on_force_created",
"defines.events.on_forces_merging",
"defines.events.on_player_cursor_stack_changed",
"defines.events.on_pre_entity_settings_pasted",
"defines.events.on_entity_settings_pasted",
"defines.events.on_player_main_inventory_changed",
"defines.events.on_player_quickbar_inventory_changed",
"defines.events.on_player_tool_inventory_changed",
"defines.events.on_player_armor_inventory_changed",
"defines.events.on_player_ammo_inventory_changed",
"defines.events.on_player_gun_inventory_changed",
"defines.events.on_player_placed_equipment",
"defines.events.on_player_removed_equipment",
"defines.events.on_pre_player_died",
"defines.events.on_player_died",
"defines.events.on_player_respawned",
"defines.events.on_player_joined_game",
"defines.events.on_player_left_game",
"defines.events.on_player_built_tile",
"defines.events.on_player_mined_tile",
"defines.events.on_robot_built_tile",
"defines.events.on_robot_mined_tile",
"defines.events.on_player_selected_area",
"defines.events.on_player_alt_selected_area",
"defines.events.on_player_changed_surface",
"defines.events.on_selected_entity_changed",
"defines.events.on_market_item_purchased",
"defines.events.on_player_dropped_item",
"defines.events.on_biter_base_built",
"defines.events.on_player_changed_force",
"defines.events.on_entity_renamed",
"defines.events.on_gui_selection_state_changed",
"defines.events.on_runtime_mod_setting_changed",
"defines.events.on_difficulty_settings_changed",
"defines.events.on_surface_created",
"defines.events.on_surface_deleted",
"defines.events.on_pre_surface_deleted",
"defines.events.on_player_mined_entity",
"defines.events.on_robot_mined_entity",
"defines.events.on_train_created",
"defines.events.on_gui_elem_changed",
"defines.events.on_player_setup_blueprint",
"defines.events.on_player_deconstructed_area",
"defines.events.on_player_configured_blueprint",
"defines.events.on_console_chat",
"defines.events.on_console_command",
"defines.events.on_player_removed",
"defines.events.script_raised_built",
"defines.events.script_raised_destroy",
"defines.events.script_raised_revive"})

add({"defines.direction.north",
"defines.direction.northeast",
"defines.direction.east",
"defines.direction.southeast",
"defines.direction.south",
"defines.direction.southwest",
"defines.direction.west",
"defines.direction.northwest"})


add({"defines.gui_type.none",
"defines.gui_type.entity",
"defines.gui_type.research",
"defines.gui_type.controller",
"defines.gui_type.production",
"defines.gui_type.item",
"defines.gui_type.bonus",
"defines.gui_type.trains",
"defines.gui_type.achievement",
"defines.gui_type.blueprint_library",
"defines.gui_type.equipment",
"defines.gui_type.logistic",
"defines.gui_type.other_player",
"defines.gui_type.kills",
"defines.gui_type.permissions",
"defines.gui_type.tutorials"})

return defines